spring:
  applicatoin:
    name: demo-api-service
  profiles:
    active: dev
    
#springboot指标检测开发指标，默认开启了/health,/info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个Package用逗号或分号分隔
#  typeAliasesPackage: com.digitalchina.sc.demo.**.entities
  #实体枚举扫描
#  typeEnumsPackage: com.digitalchina.sc.demo.**.entities.enums
  global-config:
    #主键类型 0-数据库ID自增，1-用户输入ID，2-全局唯一ID（分布式ID,19位）,3-全局唯一ID UUID
    id-type: 2
    #字段测量 0-忽略判断，1-非NULL判断，2-非空判断
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换（适用于oracle数据库）
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充测量接口实现
    meta-object-handler: com.digitalchina.sc.demo.api.base.mapper.handler.BaseMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcForNull
    jdbc-type-for-null: 'null'
    